name: $(Build.DefinitionName) $(Rev:rrrr)

trigger: none

parameters:
  - name: SolutionName
    displayName: "Solution Unique Name"
    type: string
    
  - name: CommitMessage
    displayName: "Commit Message"
    type: string

variables:
  - group: Generic Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
  - group: 'DEV Environment Variables' # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library.
  - group: 'HFXDEV Environment Variables' # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 

stages:
  - stage: exportUnpackAndCommitSolution
    displayName: 'Export, Unpack and Commit Solution'
    variables:
    - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      - group: 'DEV Environment Variables' # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
    - ${{ if eq(variables['Build.SourceBranchName'], 'hotfix') }}:
      - group: 'HFXDEV Environment Variables' # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
    jobs:
    - job: exportUnpackAndCommitSolution
      pool:
        vmImage: 'windows-latest'
      displayName: 'Export, Unpack and Commit Solution'
      steps:
      - template: ../Templates/commit-solution-template.yml
        parameters:
              SolutionName: ${{ parameters.SolutionName }}
              CommitMessage: ${{ parameters.CommitMessage }}
          
