name: $(Build.DefinitionName) $(Rev:rrrr)

trigger: none

parameters:
  - name: SolutionName
    displayName: "Solution Unique Name" #The solution to deploy
    type: string
    
  - name: CommitMessage
    displayName: "Commit Message" #A helpful message every time you deploy to tell other developers what change
    type: string

variables:
  - group: Generic Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library.
  - group: 'DEV Environment Variables' # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library.

stages:
  - stage: exportUnpackAndCommitSolution
    displayName: 'Export, Unpack and Commit Solution'
    variables:
    - group: 'DEV Environment Variables' # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
    jobs:
    - job: exportUnpackAndCommitSolution
      pool:
        vmImage: 'windows-latest'
      displayName: 'Export, Unpack and Commit Solution'
      steps:
      - template: ../Templates/commit-solution-template.yml
        parameters:
              SolutionName: ${{ parameters.SolutionName }}
              ##--> WE NEED SOMETHING HERE! The next developer won't know what changes you made during the deployment"
          
